### PR TITLE
feat: implement persistent user registration

### PR DESCRIPTION
**Pull request by akoteykula**
## Description
- Added a `register` method to `CredentialsManager` to handle new user registration.
- Implemented account storage using SharedPreferences with Gson for serialization.
- Added unit tests for the new registration functionality in `CredentialsManagerTest`.

## How to Test
- Run the unit tests for CredentialsManager.
- Register a new user via the registration screen:
- Use a new email and verify successful navigation to the login screen.
- Try to register with an existing email (case-insensitive) and ensure an error is displayed.
- Log in using the newly created account.

### CODE REVIEW

**Review by Lozu — CHANGES_REQUESTED** [review]
Notes:
1. Testing login/password (test@te.st/1234) does not work.
2. CredentialsManagerTest.kt file contains an error: Constructor for a credentialsManager variable misses "context" parameter.
3. It seems that login/password pairs are preserved between different runs of a program. I think that just makes it harder to test.

**Comment by akoteykula** [comment]
Thank you for review. I fixed this problems. Can you please check again?

**Comment by Lozu** [comment]
Now it passes all tests, but still when I provide test@te.st/1234 I get "incorrect email or password".

**Review by Lozu — APPROVED** [review]
Well, since you implemented registration, I think it would be okay to stop handling test@te.st/1234 as a special case. Approved then

**Comment by akoteykula** [comment]
Thank you

**Pull request merged**
